apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fhdw-wta

resources:
  - ../../base
  - network-demo-deployment.yaml

commonLabels:
  exercise: uebung-01
  app: network-demo
