Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/jammy64"
    config.vm.provision :docker
    
    config.vm.network "private_network", ip: "10.0.0.10"
    config.vm.provision "shell", inline: <<-SHELL
        mkdir ./root-page
        cp -r /vagrant/root-page/* ./root-page/
    SHELL
    
    config.vm.provision "docker" do |d|
        d.build_image "/vagrant", args: "-t webserver"
        d.run "webserver", args: "-p 8001:8000"
    end

end