// src/core/hooks/index.ts
export { useAnimationStep } from './useAnimationStep'
export type { AnimationStep } from './useAnimationStep'
export { useQuizState } from './useQuizState'
export { useProgress } from './useProgress'
export { useStepNavigator } from './useStepNavigator'
export type { UseStepNavigatorOptions, StepNavigatorState } from './useStepNavigator'
export { useChallengeMode } from './useChallengeMode'
export type { Challenge, UseChallengeOptions, ChallengeState } from './useChallengeMode'
export { useHighlightState } from './useHighlightState'
export type { HighlightItem, UseHighlightStateOptions, HighlightState } from './useHighlightState'
export { useGlossary } from './useGlossary'
export type { UseGlossaryOptions, GlossaryState } from './useGlossary'
export { useStudyProgress } from './useStudyProgress'
export { useFlashcards } from './useFlashcards'
export type { StudyMode, UseFlashcardsOptions } from './useFlashcards'
