apiVersion: v1
kind: Service
metadata:
  name: meta-playlist-ui
spec:
  type: NodePort
  selector:
    component: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30078
