services:
  container1:
    image: ubuntu:latest
    container_name: container1
    networks:
      small_internal_network:
        ipv4_address: 10.0.0.10
    command: >
      /bin/bash -c "apt-get update && apt-get install -y iputils-ping net-tools &&
      /bin/bash; while true; do sleep 30; done"
    tty: true

  container2:
    image: ubuntu:latest
    container_name: container2
    networks:
      small_internal_network:
        ipv4_address: 10.0.0.11
    command: >
      /bin/bash -c "while true; do sleep 30; done"
    tty: true

networks:
  small_internal_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24