apiVersion: v1
kind: Config
clusters:
- name: garden-default--workshops-external
  cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lSQU1qVk9wdUFnUUJ3NmJaMUdsYXNpV3N3RFFZSktvWklodmNOQVFFTEJRQXcKRFRFTE1Ba0dBMVVFQXhNQ1kyRXdIaGNOTWpVeE1UQTFNRGt6TURJMVdoY05NelV4TVRBMU1Ea3pNREkxV2pBTgpNUXN3Q1FZRFZRUURFd0pqWVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTHJ2Ck9Pa29iTnlmR1pNMVV4UHZmc00yNEdYTzNMclpWbjF5dUFvZ2NBR2FWK1JrdWxpQUw5MUJuRDJxYVprVXJIMHUKTGVRUkprR2E0VWZJQWpnSlRrM1kyWWczcmx1dFRlODNhRlpvS0kvSWN2WnNTUGVCdVQ2dEcvdHRmcWhUaEJsNwoxNVRUNVVZam44aFd2blpZczh5eFkxTFFIbFhnSTNPbmRpYS9zVmJEUDVrQmZhZXJvdWg4OWR0N2NKOFQ1U0RKCk1Ga256Qm1YaDNuQkRSWG1jaDNrbjZJQk9zakZGZlBsRGhLTGJodE9YVklabWwvL3lhajZUMVdreDAvdExyKzMKaW9BZjA2QlR0b2RWNXZqSVZNRVd4UHlpWTBGYy80VkdWU3JmU1FTUVR1K3p0WFdLVVpEMTJNQndQR1BhUGJtRwp4cDUzR3A4MjJKdUhTaVlmc1A4Q0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0dtTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZLaXhQMlQrdGxaa0FUZUxMVTNHc0NnRFBYSGlNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFBQld6dmQzQVlTcTVpeTBNTDBFZnNYQ0k5eWxlRUlXTEVpbzdxY3B3MVVKa01ncGVXOQpvdkYxRXdqNjlBWURCUUtPVmsyMkZNakhNRXdFS0JQdzVBd3BYYW5qY2R5SkRzTHlKSDNhbjN5VUVFYjV4UFlVCkpFSlppS29mNnhJT3Q4TEhGN3FIMnZXbDFvT2hwOFdOZzZnY00xQkl6VXQ1SVNPaWVXZ2xvYmdvOE5Pdk5CVXoKbHFKL0ZkTHVyRXJ4bXhlMXFuNnBMUHJYREhoL1d2ZzhVaHgycUU5V2ZHOUdPZmt6ZnBQZllxMXJXU3ZucmxFYgp3aUF2b0JIeWhISm85WGlyKzNXNGNHc09OZGFmQjdERWF2U2N3MWdZcGY5U0NMMlVlUWxXQXFyZW1QTmVOdFhlCmJtM0hWaUxudURwT24wUXRnS3pQeG90MTBPZGp0Rm4rcWVrbgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://api.workshops.default.s01.c01.muc1.de.bnerd.cloud
contexts:
- name: workshop17
  context:
    cluster: garden-default--workshops-external
    user: workshop17
    namespace: workshop17
current-context: workshop17
users:
- name: workshop17
  user:
    token: REDACTED_K8S_TOKEN
